[template]
# These will not be copied to users project
ignore = [
  "fill_template.rs",
  ".github/workflows/cargo-gen.yml",
]
exclude = [
  # These cause the substitution code to fail
  "assets/apple-touch-icon.png",
  "assets/favicon-16x16.png",
  "assets/favicon-192x192.png",
  "assets/favicon-32x32.png",
  "assets/favicon-512x512.png",
  "assets/favicon.ico",
  "dist",
  # These use similar syntax to Liquid and we don't have any changes we need to make
  ".github",
]

[placeholders]
crate_display_name = { prompt = "Crate display name", default = "eframe template1", type = "string" }
pwa_short_name = { prompt = "PWA Short Name", default = "egui-template-pwa1", type = "string" }
pwa_name = { prompt = "PWA Name", default = "egui Template PWA1", type = "string" }
app_struct_identifier = { prompt = "App struct identifier", default = "TemplateApp1", type = "string" }
github_repository_owner_and_name = { prompt = "Github user/organization and repo (for status badges in readme)", default = "emilk/eframe_template1", type = "string" }
