name: Create Cargo Generate Template
# Template is created on a new branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  contents: write # for committing to cargo-gen branch.

jobs:
  try_expanding_template:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: test-expand
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly # Possible issue here, needed for the single file rust script but may cause tests to fail
      - name: Replace values with placeholders
        run: ./fill_template.rs
      - uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs would fail 
      # see https://github.com/rust-lang/cargo/issues/9922
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
  create-cargo-generate-template:
    runs-on: ubuntu-latest
    needs: [ try_expanding_template ] # Only update the other branch if the test passes
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Replace values with placeholders
        run: ./fill_template.rs
      - name: Commit and Push
        run: |
          # 1. Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 2. Create/Switch to the target branch
          git checkout -b cargo-gen

          # 3. Add and commit
          git add .
          git commit -m "Replace values with template values"

          # 4. Push to the remote
          git push origin cargo-gen --force
